# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: HAactive
# label used for menu selection
label: ha_active_node
description: set up a active node in a HA deployment for PA with dedicated HA ports

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Axians

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: hostname
    description: Firewall hostname
    default: PA-01-Active
    type_hint: text
  - name: group_id
    description: Group ID du cluster
    default: 2
    type_hint: text
  - name: h1_ip
    description: Adresse IP locale pour le lien H1
    default: 1.1.1.1
    type_hint: text
  - name: h1_backup_ip
    description: Adresse IP locale pour le lien H1 de secours
    default: 2.2.2.1
    type_hint: text
  - name: h1_remote_ip
    description: Adresse IP distante pour le lien H1
    default: 1.1.1.2
    type_hint: text
  - name: h1_remote_backup_ip
    description: Adresse IP distante pour le lien H1 de secours
    default: 2.2.2.2
    type_hint: text
  - name: interface_h1_backup
    description: Interface de secours H1
    default: choices
    type_hint: dropdown
    dd_list:
      - key: ethernet1/1
        value: ethernet1/1
      - key: ethernet1/2
        value: ethernet1/2
      - key: ethernet1/2
        value: ethernet1/2
      - key: ethernet1/3
        value: ethernet1/3
      - key: ethernet1/4
        value: ethernet1/4
  - name: interface_h2_backup
    description: Interface de secours H2
    default: choices
    type_hint: dropdown
    dd_list:
      - key: ethernet1/1
        value: ethernet1/1
      - key: ethernet1/2
        value: ethernet1/2
      - key: ethernet1/2
        value: ethernet1/2
      - key: ethernet1/3
        value: ethernet1/3
      - key: ethernet1/4
        value: ethernet1/4
  - name: preemption
    description: Préemption
    default: choices
    type_hint: dropdown
    dd_list:
      - key: "yes"
        value: "yes"
      - key: "no"
        value: "no"
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
# NOTE: The following snippets are auto-generated and ordered automatically.
# Changing the content of the snippet may be necessary, but do NOT change the order

# There is a variable called snippets that we can use to auto-generate this section for us
snippets:

  - name: timezone-902240
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/system
    element: |-
        <timezone>Europe/Paris</timezone>

  - name: hostname-489441
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/system
    element: |-
        <hostname>{{ hostname }}</hostname>

  - name: entry-920966
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/interface/ethernet
    element: |-
        <entry name="{{ interface_h1_backup }}">
                      <ha/>
                    </entry>

  - name: entry-714220
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/interface/ethernet
    element: |-
        <entry name="{{ interface_h2_backup }}">
                      <ha/>
                    </entry>

  - name: high-availability-495376
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig
    element: |-
        <high-availability>
                  <interface>
                    <ha1>
                      <ip-address>{{ ip_h1 }}</ip-address>
                      <netmask>255.255.255.252</netmask>
                    </ha1>
                    <ha1-backup>
                      <port>{{ interface_h1_backup }}</port>
                      <ip-address>{{ h1_backup_ip }}</ip-address>
                      <netmask>255.255.255.252</netmask>
                    </ha1-backup>
                    <ha2/>
                    <ha2-backup>
                      <port>{{ interface_h2_backup }}</port>
                    </ha2-backup>
                    <ha3/>
                  </interface>
                  <group>
                    <group-id>{{ group_id }}</group-id>
                    <peer-ip>{{ h1_remote_ip }}</peer-ip>
                    <peer-ip-backup>{{ h1_remote_backup_ip }}</peer-ip-backup>
                    <election-option>
                      <preemptive>{{ preemption }}</preemptive>
                      <timers>
                        <recommended/>
                      </timers>
                    </election-option>
                  </group>
                  <enabled>yes</enabled>
                </high-availability>


# ---------------------------------------------------------------------
# end of snippets section